version: '3.8'

services:
  app:
    build: .
    container_name: sweet-shop-tracker-app
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sweet-shop-network
    restart: unless-stopped

networks:
  sweet-shop-network:
    driver: bridge